<div class="onestepcheckout_block">

    <div class="op_block_title" id="review"><?php echo Mage::helper('fieldsmanager')->__('Advanced Delivery') ?></div>

    <div id="checkout-review-splitfmefields">
    <div id="checkout-split-fmefields"></div>
    
    <input type="hidden" id="isSplit" name="isSplit" value="0">
    <button type="button" id="addSplitorder" class="button btn-checkout" onclick="checkout.addsplit(); return false;"><?php echo $this->__('Split Order') ?></button>
    <span id="split-please-wait" style="display:none;float:right;">

                <img src="<?php echo $this->getSkinUrl('images/onestepcheckout/opc-ajax-loader_onestepcheckout.gif') ?>" alt="<?php echo $this->__('Requesting for split...') ?>" title="<?php echo $this->__('Requesting for split...') ?>" class="v-middle" /> <?php echo $this->__('Requesting for split...') ?>

            </span>
    
    </div>
<script type="text/javascript">
    
    var spliturl = '<?php echo $this->getUrl('onestepcheckout/index/addsplit');?>';
</script>


</div>

