<!--
/*////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\  FME Fieldsmanager extension  \\\\\\\\\\\\\\\\\\\\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\ NOTICE OF LICENSE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                                                                   ///////
 \\\\\\\ This source file is subject to the Open Software License (OSL 3.0)\\\\\\\
 ///////   that is bundled with this package in the file LICENSE.txt.      ///////
 \\\\\\\   It is also available through the world-wide-web at this URL:    \\\\\\\
 ///////          http://opensource.org/licenses/osl-3.0.php               ///////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                      * @category   FME                            ///////
 \\\\\\\                      * @package    FME_Fieldsmanager              \\\\\\\
 ///////    * @author     Malik Tahir Mehmood <malik.tahir786@gmail.com>   ///////
 \\\\\\\                                                                   \\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\* @copyright  Copyright 2010 © free-magentoextensions.com All right reserved\\\
 /////////////////////////////////////////////////////////////////////////////////
 */

-->
<?php $_order = $this->getOrder() ?>

<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email=$this->__('Order confirmation email sent');
        else:
            $_email=$this->__('Order confirmation email not sent');
        endif; ?>
        <div class="entry-edit-head">
        <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
            <strong>(<?php echo $_email ?>)</strong>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td><strong><?php echo $orderAdminDate ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
            <?php if($_order->getRelationChildId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the new order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                    <?php echo $_order->getRelationChildRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRelationParentId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the previous order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                    <?php echo $_order->getRelationParentRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRemoteIp()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                <td><strong><?php echo $_order->getRemoteIp() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                    <td>
                    <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                        <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                    <?php else: ?>
                        <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                    <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                    <td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
                </tr>
                 <?php if ($_order->getCustomerInvoiceEmail()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Invoice Email') ?></label></td>
                    <td><a href="mailto:<?php echo $_order->getCustomerInvoiceEmail() ?>"><strong><?php echo $_order->getCustomerInvoiceEmail() ?></strong></a></td>
                </tr>
                <?php endif; ?>
                <?php if ($_groupName=$this->getCustomerGroupName()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                    <td><strong><?php echo $_groupName ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_dob=$this->getOrder()->getCustomerDob()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Date of Birth') ?></label></td>
                    <td><strong><?php echo Mage::helper('core')->formatDate($_dob, 'medium') ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_taxvat = $_order->getCustomerTaxvat()):?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('TAX/VAT Number') ?></label></label></td>
                    <td><strong><?php echo $this->htmlEscape($_taxvat)?></strong></td>
                </tr>
                <?php endif;?>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<?php if( $additionalData=Mage::getModel('fieldsmanager/fieldsmanager')->GetFMData($_order->getEntityId(), 'orders' , false)): ?>
    <div >
        <!--Customer's Comments-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-fieldsmanager-comment"><?php echo Mage::helper('fieldsmanager')->getheading(); ?></h4>
            </div><fieldset>
            <table cellspacing="0" class="form-list">
            <tbody>
                       
                                               
            <?php $i=0; foreach($additionalData as $info): ?>
                <?php if($i++%2==0): ?>
                    <tr>
                <?php else: ?>
                 <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <?php endif; ?>
                    <td class="label"><label><?php echo $info['label']; ?></label></td>
                    <td><strong><?php echo $info['value']; ?></strong></td>
                   
                <?php if($i%2==0 || $i==count($additionalData)): ?>
                    </tr>
                <?php endif; ?>
                    
            <?php endforeach; ?> </tbody></table></fieldset>
        </div>
    </div>
<?php endif; ?>
<div class="clear"></div>
<?php if($_order->getSplitOrder()==1):

$splits = Mage::helper('core')->jsonDecode($_order->getSplitDetail());
    if(is_array($splits)):
?>
    <style>
        #split-order td, #split-order th{border:1px solid #C1C1C1;padding: 5px !important;}
        #split-order table{float:left !important;padding: 10px !important;}
    </style>
        <div id="split-order" class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-split-order"><?php echo $this->__('Advanced Delivery'); ?></h4>
            </div>
                        <fieldset>
                          
             <?php $i=0; foreach($splits as $key => $split): ?>
                   
            <table cellspacing="0" class="form-list">
            <tbody>
                    <tr><th> <?php echo $this->__('Prdouct Name') ?></th><th> <?php echo $this->__('Delivery Date'); ?> </th><th> <?php echo $this->__('Delivery Time'); ?> </th><th> <?php echo $this->__('Cleaning Time'); ?> </th><th> <?php echo $this->__('Count')?></th></tr>
	
                    <?php  foreach($splits[$key] as $id=> $detail): ?>
                        <tr><td>
                            <?php echo $splits[$key][$id]['name']; ?>
			</td><td>
			    <?php echo $splits[$key][$id]['date']; ?>
			</td><td>
                            <?php echo $splits[$key][$id]['deliverytime']; ?>
			</td><td>
                            <?php echo $splits[$key][$id]['cleaningtime']; ?>
			</td><td>
                            <?php echo $splits[$key][$id]['count']; ?>
			</td></tr>
                    <?php endforeach; ?>
                    </tbody></table>
            <?php endforeach; ?> </fieldset>
        </div>
    <?php endif; ?>
<?php endif; ?>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
             <div class="tools"><?php echo $this->getAddressEditLink($_order->getBillingAddress())?></div>
        </div>
        <fieldset>
            <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
             <div class="tools"><?php echo $this->getAddressEditLink($_order->getShippingAddress())?></div>
        </div>
        <fieldset>
            <address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<?php endif; ?>