
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Corporate Catering, Catering, Sydney, Caterez</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="Corporate Catering, Small and Large Functions throughout Sydney. Call or Click 02 8885 0151 for priority service." />
<meta name="keywords" content="corporate catering, corporate catering sydney, catering, catering Sydney" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon" href="http://caterez.com.au/skin/frontend/default/default/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="http://caterez.com.au/skin/frontend/default/default/favicon.ico" type="image/x-icon" />
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = 'http://caterez.charuka.com/js/blank.html';
    var BLANK_IMG = 'http://caterez.charuka.com/js/spacer.gif';
//]]>
</script>
<script type="text/javascript" src="http://caterez.charuka.com/js/index.php?c=auto&amp;f=,prototype/prototype.js,prototype/validation.js,scriptaculous/builder.js,scriptaculous/effects.js,scriptaculous/dragdrop.js,scriptaculous/controls.js,scriptaculous/slider.js,varien/js.js,varien/form.js,varien/menu.js,mage/translate.js,mage/cookies.js,swfobject/swfobject.js,varien/weee.js" ></script>
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/reset.css" media="all" />

<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/boxes.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/menu.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/clears.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/print.css" media="print" />
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/iestyles.css" media="all" />
<![endif]-->
<!--[if lt IE 7]>
<script type="text/javascript" src="http://caterez.charuka.com/js/index.php?c=auto&amp;f=,lib/ds-sleight.js,varien/iehover-fix.js" ></script>
<link rel="stylesheet" type="text/css" href="http://caterez.charuka.com/skin/frontend/default/default/css/ie7minus.css" media="all" />
<![endif]-->
<style type="text/css">
#login td, #register td{
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #eee;
}
#main{ width:960px;}
#login input, #register input{
	background-color: #F8F8F8;
	border: 1px solid #666;
	padding:3px;
}
#login .submit, #register .submit{
	background-color: #6EC129;
	border: 1px solid #666;
	color: #FFF;
	padding: 4px;
}
</style>


<STYLE>
.spanstyle {
LEFT: 0px; POSITION: absolute; width: 100%; text-align: center;
}
</STYLE>


<script src="http://caterez.charuka.com/jquery.js" type="text/javascript"></script>
<script src="http://caterez.charuka.com/jquery.validate.js" type="text/javascript"></script>
<script language="JavaScript1.2">

var howOften = 5; //number often in seconds to rotate
var current = 0; //start the counter at 0
var ns6 = document.getElementById&&!document.all; //detect netscape 6

// place your images, text, etc in the array elements here
var items = new Array();
    items[0]="<a href='link.htm' ><img alt='image0 (9K)' src='http://www.caterez.com.au/1.jpg' height='314' width='950' border='0' /></a>"; //a linked image
    items[1]="<a href='link.htm'><img alt='image1 (9K)' src='http://www.caterez.com.au/2.jpg' height='314' width='950' border='0' /></a>"; //a linked image
    items[2]="<a href='link.htm'><img alt='image2 (9K)' src='http://www.caterez.com.au/3.jpg' height='314' width='950' border='0' /></a>"; //a linked image
   items[3]="<a href='link.htm'><img alt='image3 (9K)' src='http://www.caterez.com.au/4.jpg' height='314' width='950' border='0' /></a>"; //a linked image
   // items[4]="<a href='link.htm'><img alt='image4 (9K)' src='/Images/image4.jpg' height='300' width='300' border='0' /></a>"; //a linked image
   // items[5]="<a href='link.htm'><img alt='image5 (18K)' src='/Images/image5.jpg' height='300' width='300' border='0' /></a>"; //a linked image
function rotater() {
    document.getElementById("placeholder").innerHTML = items[current];
    current = (current==items.length-1) ? 0 : current + 1;
    setTimeout("rotater()",howOften*1000);
}

function rotater() {
    if(document.layers) {
        document.placeholderlayer.document.write(items[current]);
        document.placeholderlayer.document.close();
    }
    if(ns6)document.getElementById("placeholderdiv").innerHTML=items[current]
        if(document.all)
            placeholderdiv.innerHTML=items[current];

    current = (current==items.length-1) ? 0 : current + 1; //increment or reset
    setTimeout("rotater()",howOften*1000);
}
window.onload=rotater;
//-->
</script>

</head>
<body class=" cms-index-index cms-home">
<div class="wrapper">
        <!-- start header -->
        <div class="header">
            
<div class="header-top-container">
    <div class="header-top">

                <div id="logo"><a href="http://caterez.charuka.com/">
                <h1 style="text-indent:-999em;">Caterez</h1>
                <img src="http://caterez.charuka.com/media/caterez-logo.png" alt="Caterez Online" border="0" usemap="#Map" />
            <map name="Map" id="Map">
              <area shape="rect" coords="710,58,919,81" href="mailto:admin@caterez.com.au" alt="email caterez" />
            </map>
        </a></div>
        <p class="no-display"><a href="#main"><strong>Skip to Main Content &raquo;</strong></a></p>
    </div>
</div>
        </div>
        <!-- end header -->

        <!-- start middle -->
        <div class="middle-container">
            <div class="middle ">
                            <!-- start center -->

                <div>
                <!-- start content -->
                   <!-- <div id="flashcontent">
<p>You need the Latest Flash Player to view this site.</p>
<ul>
<li><a href="http://www.adobe.com/products/flashplayer/">Click here to download Flash</a></li>
<li><a href="http://www.adobe.com/products/flashplayer/">Click here if you know you have Flash</a></li>
</ul>
</div>
<script type="text/javascript">// <![CDATA[
		
         var so = new SWFObject("http://caterez.charuka.com/image_loader.swf", "sildeshow", "950", "318", "8");
	 so.addParam("wmode", "transparent");
         so.addParam("quality", "high");
         so.addParam("loop", "true");
	 so.addParam("scale", "noscale");
	 so.useExpressInstall('expressinstall.swf');
	  so.write("flashcontent");
// ]]></script>-->
<layer id="placeholderlayer"></layer><div id="placeholderdiv"></div>

		<?php echo $this->getChildHtml('content') ?>
            <!-- end content -->

                </div>
            <!-- end center -->

            </div>
        </div>
        <!-- end middle -->

<!-- start footer -->
 <div class="footer-container">
   <div class="footer"> <a href="contact-us.html" style="font-size:14px; margin-left:20px;">Contact Us</a> <a href="privacy-policy.html" style="font-size:14px; margin-left:20px;">Privacy Policy</a> <a href="refund-policy.html" style="font-size:14px; margin-left:20px;">Refund Policy</a> <a href="customer-services-policy.html" style="font-size:14px; margin-left:20px;">Customer Service Policy</a>
     <p>&copy; 2010 - 2012 Caterez Trading Pty Ltd. All Rights Reserved. ABN: 43 144 474 868 </p>
     <img src="http://caterez.charuka.com/visa_mastercard_logo.png" alt="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.facebook.com/caterez/" target="_blank"><img src="http://caterez.charuka.com/images/fb.png" /></a>&nbsp;&nbsp;&nbsp;&nbsp;</div>
 </div>
 <!-- end footer -->

</div>
</body>
</html>