<?php $_product = $this->getProduct(); ?>
<?php if(Mage::getStoreConfigFlag('advanced/modules_disable_output/CNG_Enquiry')!=1){?> 
<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>index.php/enquiry/?enquiry_sku=<?php echo $_product->sku; ?>&enquiry_product=<?php echo $_product->name; ?>" class="form-button"><span><?php echo $this->__('Enquiry') ?></span></a>
 <?php } ?> 